install: ""
php_version: ""
filesystem_version: ""
prod_install: socogas
stage_install: ""
dev_install: ""
push_environment: ""
pull_environment: ""
last_ssh_event: "2021-02-15T15:18:26-05:00"
last_push_event: "2021-02-15T15:18:20-05:00"
mysql_volume_mount_type: ""
mysql_root_password: ""
mysql_user_password: ""
mysql_user_name: ""
mysql_database_name: ""
xdebug_off_by_default: false
force_ssl: false
wp_debug: false
wp_debug_cli: false
